//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartStopDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lohnkategorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lohnkategorie()
        {
            this.Ansaetze = new HashSet<ProjektgruppeLohnkategorieAnsatz>();
            this.Personal = new HashSet<Mitarbeiter>();
            this.ProjektLohnkategorieZuordnung = new HashSet<ProjektLohnkategorieZuordnung>();
            this.RapportEintraege = new HashSet<RapportEintrag>();
            this.StartStop = new HashSet<StartStop>();
        }
    
        public string Kuerzel { get; set; }
        public string Beschreibung { get; set; }
        public decimal Standardansatz { get; set; }
        public int Lohnart { get; set; }
        public string LohnKatKontierung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektgruppeLohnkategorieAnsatz> Ansaetze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitarbeiter> Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektLohnkategorieZuordnung> ProjektLohnkategorieZuordnung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportEintrag> RapportEintraege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartStop> StartStop { get; set; }
    }
}
