//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartStopDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandantProjektZuordnung
    {
        public System.Guid MandantId { get; set; }
        public System.Guid ProjektId { get; set; }
    
        public virtual Projekt Projekte { get; set; }
    }
}
