//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartStopDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekt()
        {
            this.MandantProjektZuordnung = new HashSet<MandantProjektZuordnung>();
            this.ProjektLohnkategorieZuordnung = new HashSet<ProjektLohnkategorieZuordnung>();
            this.RapportEintraege = new HashSet<RapportEintrag>();
            this.Personal1 = new HashSet<Mitarbeiter>();
            this.StartStop = new HashSet<StartStop>();
        }
    
        public System.Guid Id { get; set; }
        public string ExternId { get; set; }
        public string Bezeichnung { get; set; }
        public string AuftragNummer { get; set; }
        public Nullable<decimal> BudgetMaterial { get; set; }
        public Nullable<System.DateTime> StartDatum { get; set; }
        public Nullable<System.DateTime> EndDatum { get; set; }
        public Nullable<short> ProjektgruppeNummer { get; set; }
        public Nullable<bool> Aktiv { get; set; }
        public Nullable<decimal> BudgetLeistungenFr { get; set; }
        public Nullable<double> BudgetLeistungenStd { get; set; }
        public Nullable<decimal> BudgetSpesen { get; set; }
        public Nullable<double> SpesenFaktor { get; set; }
        public Nullable<double> MaterialFaktor { get; set; }
        public Nullable<double> Fortschritt { get; set; }
        public Nullable<decimal> StundeAnsatz { get; set; }
        public string ProjektleiterId { get; set; }
        public string FirmenName { get; set; }
        public string FirmaZusatz { get; set; }
        public string Strasse { get; set; }
        public string HausNr { get; set; }
        public string Postfach { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Kontakt { get; set; }
        public string Anrede { get; set; }
        public string Frist { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string Rechtsmittel { get; set; }
        public string Belastung { get; set; }
        public string Entlastung { get; set; }
        public string Kostenstelle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MandantProjektZuordnung> MandantProjektZuordnung { get; set; }
        public virtual Mitarbeiter Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektLohnkategorieZuordnung> ProjektLohnkategorieZuordnung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportEintrag> RapportEintraege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mitarbeiter> Personal1 { get; set; }
        public virtual Projektgruppe Projektgruppen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartStop> StartStop { get; set; }
    }
}
