//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartStopDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektgruppeLohnkategorieAnsatz
    {
        public short ProjektgruppeNummer { get; set; }
        public string LohnkategorieKuerzel { get; set; }
        public decimal Ansatz { get; set; }
    
        public virtual Lohnkategorie Lohnkategorien { get; set; }
        public virtual Projektgruppe Projektgruppen { get; set; }
    }
}
