//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogTimeStartStopWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Projektes = new HashSet<Projekte>();
            this.MitarbeiterProjektes = new HashSet<Projekte>();
            this.RapportEintraeges = new HashSet<RapportEintraege>();
        }
    
        public string PersId { get; set; }
        public string Passwort { get; set; }
        public string AHV { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Titel { get; set; }
        public string EmailName { get; set; }
        public string Strasse { get; set; }
        public string Ort { get; set; }
        public string Postleitzahl { get; set; }
        public string Land { get; set; }
        public string TelefonPrivat { get; set; }
        public string TelefonBeruflich { get; set; }
        public string Natel { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string EhepartnerName { get; set; }
        public string NotfallkontaktPerson { get; set; }
        public string NotfallkontaktTelefon { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> Eintritt { get; set; }
        public Nullable<System.DateTime> Austritt { get; set; }
        public Nullable<decimal> AnsatzNK { get; set; }
        public Nullable<double> Ferien { get; set; }
        public Nullable<decimal> StdLohnAnsatz { get; set; }
        public string LohnkategorieKuerzel { get; set; }
        public string Rechte { get; set; }
        public double ArbeitProzent { get; set; }
        public int KalenderId { get; set; }
        public Nullable<double> StartNormalarbeitszeit { get; set; }
        public Nullable<int> Intervall { get; set; }
        public string Abteilung { get; set; }
        public string Funktion { get; set; }
        public Nullable<bool> Gleitzeitberechtigt { get; set; }
        public Nullable<bool> UseTagessollzeiten { get; set; }
        public Nullable<int> MoSollzeit { get; set; }
        public Nullable<int> DiSollzeit { get; set; }
        public Nullable<int> MiSollzeit { get; set; }
        public Nullable<int> DoSollzeit { get; set; }
        public Nullable<int> FrSollzeit { get; set; }
        public Nullable<int> SaSollzeit { get; set; }
        public Nullable<int> SoSollzeit { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> Angemeldet { get; set; }
        public string ExchangeID { get; set; }
        public Nullable<bool> OutlookKontakte { get; set; }
        public Nullable<bool> OutlookKalender { get; set; }
        public Nullable<bool> Lehrlingsbetreuer { get; set; }
        public string Kontogruppe { get; set; }
        public string Konto { get; set; }
        public string Kore { get; set; }
        public string IRKonto { get; set; }
        public string IRKore { get; set; }
    
        public virtual Lohnkategorien Lohnkategorien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekte> Projektes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projekte> MitarbeiterProjektes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportEintraege> RapportEintraeges { get; set; }
    }
}
