//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogTimeStartStopWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektLohnkategorieZuordnung
    {
        public System.Guid ProjektId { get; set; }
        public string Kuerzel { get; set; }
        public Nullable<decimal> Ansatz { get; set; }
        public string ProjektLohnKatKontierung { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    
        public virtual Lohnkategorien Lohnkategorien { get; set; }
        public virtual Projekte Projekte { get; set; }
    }
}
