//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogTimeStartStopWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapportEintraege
    {
        public System.Guid Id { get; set; }
        public System.DateTime Datum { get; set; }
        public System.Guid MandantId { get; set; }
        public System.Guid ProjektId { get; set; }
        public string PersId { get; set; }
        public string Text { get; set; }
        public string LohnkategorieKuerzel { get; set; }
        public string TarifkategorieId { get; set; }
        public double Aufwand { get; set; }
        public Nullable<decimal> AnsatzIntern { get; set; }
        public Nullable<decimal> AnsatzExtern { get; set; }
        public double Zuschlag { get; set; }
        public int Verrechnet { get; set; }
        public int ArbeitsRapportNr { get; set; }
        public string TimeIntervall { get; set; }
        public string ErfName { get; set; }
        public Nullable<System.DateTime> ErfDatum { get; set; }
        public string MutName { get; set; }
        public Nullable<System.DateTime> MutDatum { get; set; }
        public string LohnKatKontierung { get; set; }
    
        public virtual Lohnkategorien Lohnkategorien { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Projekte Projekte { get; set; }
        public virtual Tarifkategorien Tarifkategorien { get; set; }
    }
}
