//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogTimeStartStopWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartStop
    {
        public int Id { get; set; }
        public string PersId { get; set; }
        public System.Guid ProjektId { get; set; }
        public string LohnkategorieKuerzel { get; set; }
        public string TarifkategorieId { get; set; }
        public string TimeIntervall { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
